name: aval1_prog2
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/TeofiloAlbuquerque/aval1_prog2

environment:
  sdk: ^2.19.6

# Add regular dependencies here.
dependencies:
  xml: ^6.3.0
  csv: ^5.0.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
